// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS1spfcBKuqBQ3Zt8vCH4pOMVyCCZmB7k',
    appId: '1:499026946457:web:6bde985a8b2e33c6c0cb08',
    messagingSenderId: '499026946457',
    projectId: 'noah-door-2',
    authDomain: 'noah-door-2.firebaseapp.com',
    databaseURL: 'https://noah-door-2-default-rtdb.firebaseio.com',
    storageBucket: 'noah-door-2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2GbHc22DLdCouvqA5S95rwsEUjvY_qXk',
    appId: '1:499026946457:android:334ca391d3222e95c0cb08',
    messagingSenderId: '499026946457',
    projectId: 'noah-door-2',
    databaseURL: 'https://noah-door-2-default-rtdb.firebaseio.com',
    storageBucket: 'noah-door-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfapDpkKtvb0k5Q2zAbZuSqX2nMcd8gjM',
    appId: '1:499026946457:ios:c6e46362fdc641e8c0cb08',
    messagingSenderId: '499026946457',
    projectId: 'noah-door-2',
    databaseURL: 'https://noah-door-2-default-rtdb.firebaseio.com',
    storageBucket: 'noah-door-2.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfapDpkKtvb0k5Q2zAbZuSqX2nMcd8gjM',
    appId: '1:499026946457:ios:c6e46362fdc641e8c0cb08',
    messagingSenderId: '499026946457',
    projectId: 'noah-door-2',
    databaseURL: 'https://noah-door-2-default-rtdb.firebaseio.com',
    storageBucket: 'noah-door-2.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS1spfcBKuqBQ3Zt8vCH4pOMVyCCZmB7k',
    appId: '1:499026946457:web:d1c7f4291d0eafcbc0cb08',
    messagingSenderId: '499026946457',
    projectId: 'noah-door-2',
    authDomain: 'noah-door-2.firebaseapp.com',
    databaseURL: 'https://noah-door-2-default-rtdb.firebaseio.com',
    storageBucket: 'noah-door-2.firebasestorage.app',
  );

}